use core::fmt;
use std::fmt::write;

#[derive(Debug)]
pub enum Http1Error {
    CreateSocketError(i32),
    BindSocketError(i32),
    ListenError(i32),
    AcceptError(i32),
    NoActiveConnection,
}

impl Http1Error {
    fn unpack_err(&self, code: &i32) -> &'static str {
        match code.abs() {
            9 => "EBADF : Bad file descriptor",
            13 => "EACCESS : Permission denied",
            98 => "EADDRINUSE : Address already in use",
            22 => "EINVAL : Invalid argument",
            24 => "EMPFILE : Too many open files",
            32 => "EPIPE : Broken pipe",
            _ => "unknown error, check with : errno -l {code}",
        }
    }
}

impl fmt::Display for Http1Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::CreateSocketError(code) => {
                write!(f, "Socket creation failed: {}", self.unpack_err(code))
            }
            Self::BindSocketError(code) => write!(f, "Binding failed: {}", self.unpack_err(code)),
            Self::ListenError(code) => write!(f, "Listen failed: {}", self.unpack_err(code)),
            Self::AcceptError(code) => write!(f, "Accept failed: {}", self.unpack_err(code)),
            Self::NoActiveConnection => write!(f, "No active connection to operate on"),
        }
    }
}

// fom linux manpages " man 2 socket "
// ERRORS
//        EACCES Permission to create a socket of the specified type and/or protocol is denied.
//        EAFNOSUPPORT The implementation does not support the specified address family.
//        EINVAL Unknown protocol, or protocol family not available.
//        EINVAL Invalid flags in type.
//        EMFILE The per-process limit on the number of open file descriptors has been reached.
//        ENFILE The system-wide limit on the total number of open files has been reached.
//        ENOBUFS or ENOMEM Insufficient memory is available.  The socket cannot be created until sufficient resources are freed.
//        EPROTONOSUPPORT The protocol type or the specified protocol is not supported within this domain.
//        Other errors may be generated by the underlying protocol modules.
